### ISSUE TITLE
scale not appearing correctly on Safari

### ISSUE THREAD

**Issue by mcdonaldajr** [colinl/node-red-dashboard-2-ui-gauge-classic#5]
![Image 25-06-2024 at 16 53](https://github.com/colinl/node-red-dashboard-2-ui-gauge-classic/assets/4070175/5aec0f02-c0c6-4f4b-a56c-20d85e0a66e1)

works fine on Chrome. Error appears on Safari on Mac and iPhone.

**Comment by colinl** [comment]
I am not particularly surprised.  Safari has problems with lots of stuff.  There is nothing I can do about it, you will have to use a browser that supports modern javascript and CSS.

**Comment by mitchtimken** [comment]
I am seeing the same issue on multiple iOS browsers (Safari, Google Chrome, and Firefox). Works fine on PC as far as I am aware.

**Comment by colinl** [comment]
> Works fine on PC as far as I am aware.

I don't understand why you have said 'as far as I am aware'.  If you view the same node red server on a PC and on iOS with Chrome does the same gauge work ok when viewed on the PC and not on iOS?

If you open the browser developer tools console on iOS using Chrome do you see any errors reported?

Not having access to a machine running iOS it is difficult for me to debug.

**Comment by mitchtimken** [comment]
Sorry for poor phrasing. I just started testing with this node earlier today. When viewing the same node red server on a PC and on iOS with Chrome, the gauge works fine on PC with corresponding scale in the right spot. On iOS, the needle moves and the value is correctly displayed but the scale is not in the right spot (exactly what is shown in original post). 

I opened browser developer tools console within Chrome on iOS and did not encounter any errors when viewing the dashboard and injecting test values to the gauge node. Within node red, I also tried re-deploying a few times and restarted node red but issue was still not resolved. I am not very comfortable with iOS myself but let me know if I can be of more assistance.

**Comment by colinl** [comment]
What version of chrome is it?

**Comment by mitchtimken** [comment]
Chrome Version 126.0.6478.153 (Official Build) stable (64-bit)

**Comment by colinl** [comment]
Well that is not the issue, I have an old Android tablet running Chrome 106 and it is fine.  I have [posted a question on the forum](https://discourse.nodered.org/t/d2-display-problems-on-ios/89253) to see if anyone there has any suggestions.

**Comment by hotNipi** [comment]
Things to try

Currently for numbers the CSS applies like this
```
rotate: -48deg;
transform-origin: 50% 42.6667%;
transform: translate(50%, 42.6667%);
```

You may move the transform into one rule (not too far ago that was the only option)
```
transform-origin: 50% 42.6667%;
transform: rotate(-48deg) translate(50%, 42.6667%);
```

**Comment by colinl** [comment]
> You may move the transform into one rule

Thanks, I will release a new version with that changed later today in the hope it helps.

@mitchtimken did you see the post on the forum, that in fact all browser on iOS are rendered using the Safari engine, explaining why they all have problems.

**Comment by colinl** [comment]
@mcdonaldajr, @mitchtimken I have released version 1.1.2 with simplified CSS, which might, or might not, make a difference with iOS.  You should be able to install it via Manage Palette (you might have to refresh the browser page to see it). Then restart node red and refresh the browser page viewing the dashboard and see if it has helped.

**Comment by mcdonaldajr** [comment]
Mac running Safari - same problem. Note: tried it on Chrome on an iPhone, also didn’t work properly.
Mac running Chrome- works as designed.


￼￼

**Comment by hotNipi** [comment]
Here's the thing:
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin

Safari & Safari on iOS

_Only supported for transformations applied using the CSS transform property (e.g. .className { transform: rotate(45deg); transform-origin: center; }). It has no effect on transformations applied using the transform SVG attribute (e.g. `<rect style="transform-origin: center;" transform="rotate(45)" />`)._


So what you maybe can do is to turn those transform related calculations into CSS variables and use them in the class for numbers.

**Comment by colinl** [comment]
OK, thanks, does that mean I will have to dynamically create a unique class for each number, along with the CSS for that class?

**Comment by hotNipi** [comment]
No. But it is not something I can explain without example but I'm away from computer for this weekend..

**Comment by colinl** [comment]
I am away for a few days too, so that is not a problem.

**Comment by colinl** [comment]
@mcdonaldajr, @mitchtimken I have released version 1.1.3 with @hotNipi's suggestions. Could you give that a go?

**Comment by mcdonaldajr** [comment]
I’m away at present, but will give it a go when I’m back. Cheers, AnthonyOn 9 Jul 2024, at 10:02, Colin Law ***@***.***> wrote:﻿
@mcdonaldajr, @mitchtimken I have released version 1.1.3 with Bart's suggestions. Could you give that a go?

**Comment by mitchtimken** [comment]
![gauge_ios](https://github.com/colinl/node-red-dashboard-2-ui-gauge-classic/assets/106117488/46ff092b-e68b-4203-b63f-b937fd7d2a74)
I installed version 1.1.3 and gave it a go. I am still having the same issue on iOS browsers. I restarted node-red a few times and I tried injecting a few different test values. I also checked browser developer tools console and again didn't see any errors.

**Comment by colinl** [comment]
I think I may need to use the same method for the scale text that I use for the needles, which do work apparently.
I will have a look at that.

**Comment by colinl** [comment]
@mcdonaldajr, @mitchtimken - @hotNipi has suggested some further changes, released in v1.1.4, if you would like to give that a go.

**Comment by mitchtimken** [comment]
Issue seems to be resolved on iOS browsers (Safari, Chrome, Firefox). Both needle and scale work as intended. Thanks everyone for all your assistance in getting this bug resolved. @colinl @hotNipi @mcdonaldajr

**Comment by colinl** [comment]
Excellent. Credit goes to @hotNipi for the fix.

**Comment by mcdonaldajr** [comment]
I can confirm (probably unnecessarily) that it works correctly on Mac as well.

Thanks, Anthony

￼

**Comment by colinl** [comment]
Thanks for confirming that.

**Comment by mcdonaldajr** [comment]
Colin, having fun with your gauge. Managed to colour the temperature to indicate if too hot or too cold, plus use the needle hub to indicate if a vessel is powered up or not.

Only one issue is the large space underneath the dials. I’d welcome your advice on how to reduce it. I’ve tried every combination of group and gauge sizes. I’m trying to display this on a 800 x 480 raspberry pi screen, but the white space is a problem. Any ideas?

Best Regards, Anthony

**Comment by colinl** [comment]
Post an image please and show us  the settings in the node.

**Comment by mcdonaldajr** [comment]
Colin,

Thanks for responding. Here is the flow and subflow.

￼

Attached are the screen shots of the dashboard, the dial node settings, which are in a subflow, so I’ve also attached the “calling” node. Also the group and page dashboard settings.
I use a subflow, as I have dozens of gauges, and don’t want to duplicate the code. I tested it with Safari and Chrome. The displays are identical. I tried 3x2 size but it cuts off the bottom of the gauge. I also tried 6x5 but the gauges were then too big to fit onto the 800 x 480 raspberry pi screen. It’s possible that this is a Dashboard 2 bug, rather than any issues with your dial. That is what I will explore next.

Best Regards, Anthony
￼
￼
￼
￼

￼

**Comment by colinl** [comment]
Your images are not visible, to me at least.
All I need is a screenshot of what it looks like and a screenshot of the gauge config.  No flows necessary

**Comment by colinl** [comment]
Oh, and also whether you are using Fixed or Grid layout for the Page.

**Comment by mcdonaldajr** [comment]
Colin,

Try these jpeg(s).

I tried Grid and Fixed. These examples are using grid, as you’ll see from the 5th image. Used Chrome browser.
6th image shows the dials alongside a standard dashboard 2 gauge.


Anthony

**Comment by mcdonaldajr** [comment]
Colin,

It seems the issue is the inclusion of the gauge in a subflow. See below. Dial1 and Dial2 are in a subflow. Dial3 and Dial4 are not. Dial5 is in a subflow. Note the unwanted white space above it.

Looks like I need to report this to the Dashboard 2 team.

Anthony

**Comment by colinl** [comment]
I am still not seeing any images. You should just be able to copy/paste an image here.

**Comment by mcdonaldajr** [comment]
Apologies, I was replying to the email, and the images don't get added to GitHub for some reason.

It seems the issue is the inclusion of the gauge in a subflow. See below. Dial1 and Dial2 are in a subflow. Dial3 and Dial4 are not. Dial5 is in a subflow. Note the unwanted white space above it.

Looks like I need to report this to the Dashboard 2 team.
![2](https://github.com/user-attachments/assets/002a7e13-1ee0-4506-b549-c380ad711e8f)


![Image 15-07-2024 at 12 11 (2)](https://github.com/user-attachments/assets/414dedad-386e-421f-bbc5-1570204faf8c)

**Comment by colinl** [comment]
It does appear that having it in a subflow is the problem.  I suggest [submitting an issue against the dashboard](https://github.com/FlowFuse/node-red-dashboard/issues).  Use the core gauge for that so that it is not necessary to install anything to see the problem.

You mentioned fitting it into a 3x2 space.  If you reduce the sweep angle to 220 then that works reasonably well.  Also clear the Label and Measurement so that it puts the gauge at the top and puts the value above the hub.

![image](https://github.com/user-attachments/assets/f6c4f179-2b87-4aa0-8501-6ac0cdfc1079)

**Comment by mcdonaldajr** [comment]
It is not the subflow! I have found the problem. It is the including of a Template node in the same group somehow increases the size of the group, even when the Template node size is set to 0 x 0. This occurs whether the template node is in a sub flow or not. I will report this to dashboard team. Thanks for your time in looking into this.

**Comment by mcdonaldajr** [comment]
I also took the advice above, and after temporarily disabling the template node (until the issue is addressed by the dashboard team) I now have a fully functioning brewery control panel. Many Thanks.
![IMG_2874](https://github.com/user-attachments/assets/c6748d35-b4ce-4524-ab11-2c1a2c3ca2d0)

**Comment by colinl** [comment]
Excellent. It is a pity that the needles get chopped off when the value is offscale in that mode, but I don't think the overheads of the rather complex maths to stop it would be worth while.

**Comment by hotNipi** [comment]
-- needles get chopped off when the value is offscale
But that can freely be option to turn off.

**Comment by colinl** [comment]
I think it is important that the user can distinguish between valid and invalid data.  If the needles were just clamped at the end points then it is impossible to distinguish between a valid value at the end of the range and invalid or out of range data. Having thought about it, it probably isn't too difficult to stop the needle getting truncated.  I have raised an issue to get this done when I have some time. #8

**Comment by mcdonaldajr** [comment]
I agree. I like to set min and max for the normal ranges where I need some precision. Having a visual indication that the value is outside them is important.

**Comment by hotNipi** [comment]
Agree as for being off scale should be indicated but must it be needle to take that responsibility? As in this case the outcome requires layout to be different but is it really case of such trade?

**Comment by colinl** [comment]
> but must it be needle to take that responsibility?

I think so, yes.  This is supposed to be a representation of a physical gauge, where there is only the needle, banging against the end stop.

**Comment by mcdonaldajr** [comment]
Problem of the template node increasing the size of the group is solved by choosing CSS (Single Page) as the Type on the template node.
